# Generated by Django 6.0.3 on 2026-04-02 11:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0004_remove_order_quantity_received_alter_order_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_received', models.PositiveIntegerField(verbose_name='Количество получено (шт)')),
                ('actual_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Фактическая цена закупки (ед)')),
                ('delivery_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время приемки')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий (номер накладной и т.д.)')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='orders.order', verbose_name='Заказ-основание')),
            ],
            options={
                'verbose_name': 'Приемка товара',
                'verbose_name_plural': 'Приемки товара',
            },
        ),
    ]
