# Generated by Django 6.0.3 on 2026-04-04 12:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Цена закупки (ед)')),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена продажи')),
                ('status_card', models.CharField(choices=[('CANDIDATE_IN_REQUEST', 'Кандидат в заявку'), ('IN_REQUEST', 'В заявке'), ('IN_DELIVERY', 'В доставке'), ('ARRIVED', 'Прибыл')], default='CANDIDATE_IN_REQUEST', max_length=30, verbose_name='Статус документооборота')),
                ('status_physical', models.CharField(choices=[('NOT_ARRIVED', 'Ещё не прибыл'), ('IN_STORE', 'На складе'), ('SOLD', 'Продан'), ('CREDIT', 'В кредит'), ('LOST', 'Потерян'), ('IN_DISASSEMBLED', 'Разобран'), ('IN_COLLECTED', 'Собран')], default='NOT_ARRIVED', max_length=30, verbose_name='Физический статус')),
                ('on_stock', models.BooleanField(default=False, verbose_name='На складе')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('received_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата приёмки')),
                ('sold_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата продажи')),
                ('returned_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата возврата')),
                ('credit_paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата оплаты кредита')),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Серийный номер')),
                ('product_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Код товара (кэш)')),
                ('product_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название товара (кэш)')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_units', to='orders.customer', verbose_name='Покупатель (если предзаказ)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='products.product', verbose_name='Товар')),
                ('source_order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='units', to='orders.orderitem', verbose_name='Позиция в заявке')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplied_units', to='orders.supplier', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Единица товара',
                'verbose_name_plural': 'Единицы товара',
                'ordering': ['-created_at'],
            },
        ),
    ]
