# Generated by Django 6.0.3 on 2026-04-02 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productunit',
            options={'ordering': ['-created_at'], 'verbose_name': 'Единица товара', 'verbose_name_plural': 'Единицы товара'},
        ),
        migrations.AddField(
            model_name='productunit',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Цена закупки (ед)'),
        ),
    ]
